### PR TITLE
Add mpich-mpicc as dependency for mpich builds

### PR DESCRIPTION
**Pull request by xylar**
Update the license to match the upstream repository.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
LGTM, merge?

**Comment by xylar** [comment]
@ocefpaf, I'd still like to get clarity on whether this is the preferred solution to the problem we had in #112.  Let's hold off just a bit.

**Comment by xylar** [comment]
I didn't get the feedback I was hoping for but I think we can go ahead with this solution for now and implement a preferred solution if there is one later on.

**Pull request merged**
