### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by djhoese**
Need to pick up HDF5 1.10.4 in build process. See https://github.com/conda-forge/h5py-feedstock/pull/46 and https://github.com/conda-forge/gdal-feedstock/pull/243 for reference. Bottom line: can't install new/fixed gdal in a Windows environment if netcdf4 and/or h5py are installed since they are built with old HDF5.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by djhoese** [comment]
@conda-forge-admin, please rerender

**Comment by djhoese** [comment]
Windows Python 2.7 failed with:

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'libnetcdf=4.6', 'hdf5=1.10.4', 'python=2.7'}
```

Ideas? Does the `libnetcdf` requirement need to be relaxed?

**Edit:** I'm not really sure what is going on here. What other dependency could be causing this? The `libnetcdf` and `hdf5` versions aren't hardcoded.

**Comment by ocefpaf** [comment]
> Ideas? Does the libnetcdf requirement need to be relaxed?

Not really. vc9 should be abandoned. What is happening is that latest libnetcdf, built with latest hdf5, won't compile with the old vc9 for legacy Python on Windows.

**Comment by djhoese** [comment]
@ocefpaf Yep, @kmuehlbauer just mentioned that on the issue I made for libnetcdf (see https://github.com/conda-forge/libnetcdf-feedstock/issues/65).

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by djhoese** [comment]
@ocefpaf FYI, skipping python 2.7 on Windows for this package will mean library loading issues for environments that have `netcdf` and `gdal` installed in the same environment unless all of the `gdal` packages that aren't specifically tagged as `vc9` are marked as broken.

**Comment by ocefpaf** [comment]
> @ocefpaf FYI, skipping python 2.7 on Windows for this package will mean library loading issues for environments that have `netcdf` and `gdal` installed in the same environment unless all of the `gdal` packages that aren't specifically tagged as `vc9` are marked as broken.

We may have badly pinning packages but that should not be a problem as long as I identify them. Conda-build 3 adds the proper metadata and conda should be able to install the old version that are properly pinned.

**Comment by djhoese** [comment]
Thanks. I'll try to let you know if I run in to any more issues. We'll see what happens after this is PR is merged. 🤞

**Comment by djhoese** [comment]
Restarted travis job that seems like it got stuck.

**Comment by djhoese** [comment]
@ocefpaf I think this is ready for merge.

**Comment by ocefpaf** [comment]
Thanks @djhoese!

**Pull request merged**
