### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative to #54

### CODE REVIEW

**Comment by ocefpaf** [comment]
I'm still getting this on Windows:

```
running run_test.py
Traceback (most recent call last):
  File "C:\bld\netcdf4_1533591041699\test_tmp\run_test.py", line 5, in <module>
    import netCDF4
  File "C:\bld\netcdf4_1533591041699\_test_env\lib\site-packages\netCDF4\__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: DLL load failed: The specified module could not be found.
(C:\bld\netcdf4_1533591041699\_test_env) C:\bld\netcdf4_1533591041699\test_tmp>IF 1 NEQ 0 exit 1 
```

@gillins could it be related to https://github.com/conda-forge/libnetcdf-feedstock/pull/49#discussion_r207753449 ? I ended up not applying that patch b/c I thought we don't need it on AppVeyor, but maybe we do :-/

**Comment by gillins** [comment]
Hmm maybe - I'll have a look tomorrow. In general I'm not a fan of using `INCLUDE(InstallRequiredSystemLibraries)` in `cmake` since this means all the MS runtime files get put into the package also, AppVeyor or not (I'm sure others will know more). This is redundant since conda already installs them and in `qgis` made the install step fail (not sure why it was ok here).

**Comment by ocefpaf** [comment]
> Hmm maybe - I'll have a look tomorrow. In general I'm not a fan of using `INCLUDE(InstallRequiredSystemLibraries)` in `cmake` since this means all the MS runtime files get put into the package also, AppVeyor or not (I'm sure others will know more). This is redundant since conda already installs them and in `qgis` made the install step fail (not sure why it was ok here).

I don't really know what that entails but I trust your jugdment. I'm adding that patch in the next PR.

**Comment by ocefpaf** [comment]
Waiting on the outcome of https://github.com/conda-forge/libnetcdf-feedstock/pull/50#issuecomment-411218622 before we re-start things here.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@kalefranz and @msarahan just to provide a data point: using https://github.com/conda-forge/netcdf4-feedstock/pull/55/commits/10238ab136094c67bb55ad6d0fc62b46f53b23ef fixed the AppVeyor here. I haven't looked at the logs yet though to check if things as 100% OK.

**Comment by ocefpaf** [comment]
I'm merging this to get the latest version out but this is currently relying on a workaround.

**Pull request merged**
