### PR TITLE
nompi build can use MPI or no-MPI variants at runtime

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
In some of my testing where I want parallel versions of `libnetcdf` and `hdf5` but I don't need the parallel version of `netcdf4`, I'm running into trouble when trying to run python code without `mpirun` even when it is ostensibly serial code.  These changes should allow me to explicitly say that I want the MPI versions of `libnetcdf` and `hdf5` without having to also pick up the MPI version of `netcdf4`, e.g.:
```
conda create -y -n test python=3.7 "libnetccf=*=mpi_mpich_*" "hdf5=*=mpi_mpich_*" \
   "netcdf=*=nompi_*"
```

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I will do some local testing of these changes.  @conda-forge/netcdf4, any objections to them?  If not, I'll merge as soon as I'm done with my local testing.

**Comment by xylar** [comment]
This worked great in my local tests.  I was able to create a conda environment with `mpich` variants of `libnetcdf`, etc. but the `nompi` version of `netcdf4` and the difficulties I'd been having with `netcdf4` went away!

@conda-forge/netcdf4, any objections to me merging this?  If I don't hear anything by this time tomorrow, I'm going to go ahead.

**Comment by ocefpaf** [comment]
Thanks for fixing this @xylar!

**Pull request merged**
