### PR TITLE
Sane numpy

### PR DESCRIPTION
**Pull request by kain88-de**
sane numpy config. Add python 3.4 to build matrix

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kain88-de we'll need latest `libnetcdf` and its dependencies for `vc10` to get `Python 3.4` here correctly.
I'll look into it.

**Comment by kain88-de** [comment]
How is that related?

**Comment by ocefpaf** [comment]
`Python 3.4` uses `vc 10`, see https://conda-forge.org/docs/buildwin.html#vc-features, and we need version of the updated dependencies compiled with `vc 10`. We can probably find the old ones in the channel, but I highly recommend to use the latest versions of the dependencies.

PS: the failure you are seeing though is unrelated.  It is because `AppVeyor` no longer has `miniconda` for `Python 3.4`. You will need to manually change that like [this](https://github.com/conda-forge/matplotlib-feedstock/pull/124/commits/58d50c6ac6695f3bc8cdad892d4a4e9ab532dd3a) and let `miniconda` download `Python 3.4` at build time.

**Comment by ocefpaf** [comment]
Done in #37

**Pull request closed without merging**
